---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-secret
  namespace: default
spec:
  encryptedData:
    password: AgBAqEToN0yxkzOnNIhFW8PDHpyOedCF5+TnIe0P0GJRYaAkMjw/+UsdKW36EIF0/Bn1DPeixHZ4ldPdKP5iHlZ5PpKOQJYFwefmlEBPvpYRzJcKQEkLc2g/MQ6jc+p/cMmKjEVTT92Ehhls+cEb1oJuLVBqIMqWbK7On+moEOHKM2nEkNfs65rftG//tDzErczctT6DFLDtYcflTWUAt5MKWQgLPg0nL9oSixyWeeXL9DN7KrNU6hub022PuX99Us1WjJ13reTeOTz97wNFUeLW62PxUvazX5Q5r1JBybzqn22imYTG63icjhHPk8kn3Xk+LDhUClcaC8yFqY2gc3fwRS9uexmSRp/6JuFLSNtu9UjXMseCAn1Snjaiy6uGuNKegVoH5EE7NZD85Abf4tBFJlYXEV6EJuq/7gL8o7vdSIGbiwNN/5pkNcZG67UK2H+ypxy2muz0oWjaDAk06hz/OuJnUIxeMorhSVzRbtBeEOovJiF4Zwg2+omoCCUooSJ4ElO1Yijs2V7pMycY/hKgAaF0cFJtTw+VLILVFRCUI1r17KMpMlqL44fgQ1SBTZe77geHlQVSX/8bWKPHLheNq6cXZfdMtE/W2C/I5cPtTMPc7jlqfQeZiy9EU5W1zw2X2/BBMr2UF4OaJJQtaN6AeNZAOmZVQ03iaOTvPF+n4WqqZDBGbTwBwEuCBNPqZUoh2qAN2VQ7ow==
  template:
    metadata:
      name: db-secret
      namespace: default
    type: Opaque
